apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
spec:
  template: 
    spec:
      containers:
      - image: new-image
        name: new-app
        securityContext:
          allowPrivilegeEscalation: true
          runAsUser: 0
